spring:
  application:
    name: academy-spring-2Corsi

  datasource:
    url: jdbc:postgresql://localhost:5432/academy_elite_corso
    username: postgres
    password: Lemuel05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  error:
    include-stacktrace: always

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

        #http://localhost:8081/swagger-ui/index.html
        #http://localhost:8081/v3/api-docs
